### ISSUE TITLE
Feat: 소셜 로그인 기능 추가

### ISSUE THREAD

**Issue by go-hoon** [bsideproject/palette-auth-server#1]
소셜 로그인과 관련된 AuthController, AuthService 추가했습니다.
OauthManager를 기반으로 소셜 로그인을 진행합니다.
현재 GoogleOauthManager를 추가했고 테스트 해봤습니다.
당장은 user의 email만을 받아오도록 만들었습니다.
다른 방식의 소셜 로그인을 하더라도 email이 같다면 같은 유저로 취급하도록 했습니다.

또한 jwtProvider에서 jwt관련 기본적인 로직을 준비했습니다.

**Comment by jikimee64** [comment]
@Player1789 
email 저장시 @kakao.com, @google.com 와 같은 도메인도 같이 저장하는 방식일까요?
소셜 로그인에서 user의 email 반환 형식이 궁금하네요!

'다른 방식의 소셜 로그인을 하더라도 email이 같다면 같은 유저로 취급'
위와 같은 방식으로 할 경우 앱 내의 데이터가 동기화 되는 경우가 생길 수도 있을것 같아요.
(email 저장을 도메인을 제외한 아이디만 저장할 경우..)
개인적인 생각으론 각각의 소셜 로그인 별로 새로운 유저로 봐야되지 않을까 조심스럽게 생각이 드네요.

각 소셜 로그인에서 반환하는 유저별 고유한 키 값 + social 로그인 타입으로 유저를 구분하면 어떨까 합니다!

**Comment by go-hoon** [comment]
@jikimee64 
질문과 의견 감사드려요! 
email은 사용자가 각 소셜 서비스에 가입할 때 사용했던 email이고 도메인도 같이 저장하고 있어요.
예를 들어 내가 카카오나 페이스북 로그인시 사용하는 이메일이 abcd1234@gmail.com 라면 우리 DB에 저장하는 이메일이 abcd1234@gmail.com이 되는거죠.

이메일이 같다면 같은 유저로 취급하게 구현한 이유는, (이게 안되는 서버스들을 사용하면서 들었던 생각인데)
1. 다시 로그인 할 때 마다 내가 이 서비스에 카카오로 로그인을 했나? 구글로 했나? 하고 항상 헷갈리고 여러번 시도하게 되더라구요. (유저 입장에선 로그인했는데 내가 쓰던 데이터가 없으면 '데이터가 다 지워진건가?' 하기도 하구요)
2. 그리고 소셜별로 다른 유저라고 본다면, 일기에 친구를 초대할 때 '내 친구의 구글 계정' 또는 '내 친구의 카카오 계정'을 따로 초대 해야할 것 같아요.

이 두가지 상황이 유저 경험을 해치지 않을까 생각해서 '같은 이메일이라면 같은 유저로' 취급하게 만들었어요.
어떻게 생각하시나요?

그리고 '앱 내의 데이터가 동기화 되는 경우'가 어떤 상황인지 자세하게 알려주실 수 있을까요?

혹시 다른 의견도 있으시면 말씀 주세요!

**Comment by jikimee64** [comment]
@Player1789
답변 감사합니다!
결론은 기획팀 의견도 들어보고 결정해야될 것 같아요!
아래는 답변해주신 내용에 대한 제 생각입니다. 😊

1. 다시 로그인 할 때 마다 내가 이 서비스에 카카오로 로그인을 했나? 구글로 했나? 하고 항상 헷갈리고 여러번 시도하게 되더라구요. (유저 입장에선 로그인했는데 내가 쓰던 데이터가 없으면 '데이터가 다 지워진건가?' 하기도 하구요)
> 헷갈리는 점은 공감이 되네요! 그치만 저희는 2개의 소셜 플랫폼만 제공하기 때문에 헷갈리는 문제는 덜하지 않을까 조심스럽게 생각합니다.. 또한 같은 앱이라도 소셜 계정별로 다른 목적으로 사용할 수 도 있지 않을까 생각해서 이메일이 같다 할지라도 다른 유저로 봐야 하지 않을까 생각해봤습니다.
ex) 카카오톡 계정 > 가족용
     페이스북 계정 > 친구용

2. 소셜별로 다른 유저라고 본다면, 일기에 친구를 초대할 때 '내 친구의 구글 계정' 또는 '내 친구의 카카오 계정'을 따로 초대 해야할 것 같아요.
> 아이디 검색을 통해서 초대하는 방식으로 간다면 충분히 이슈사항이 되겠네요! 다른 방법으로 일기장에 접근할 수 있는 초대코드를 통한 방식이면 해결이 될것 같긴해요! 초대 방식은 1번이 어떻게 픽스되냐에 따라 정해야 될것 같네요 😀

3. 앱 내의 데이터가 동기화 되는 경우
> 1번이랑 관련된 이야기인데, 카카오톡 계정으로 접근해서 작성한 일기장이 페이스북 계정으로 접근했을때 보이는 현상입니다!

**Comment by jikimee64** [comment]
@Player1789 
통합 로그인 방식으로 확정된 후 코드 확인해봤습니다.
소셜 타입을 별도의 테이블로 분리하는게 통합 로그인 방식에 맞는거 같아요!
소셜 타입 테이블은 말그대로 소셜 타입만 저장하기 때문에 값타입 컬렉션(@ElementCollection)을 써도 문제 없을 것 같아요.

추가로 테이블명만 아래처럼 수정하면 어떠실까요?
- 테이블 명 수정
  - user_social_types -> social_types
- 칼럼명 수정
  - social_types -> social_type
